name: APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python (safe method)
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv

    - name: Check Python
      run: python3 --version

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython kivy

    - name: Build APK
      run: |
        buildozer -v android debug
